<?php

namespace Database\Seeders;

use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // **Create Super Admin User**
        $superAdmin = User::create([
            'name' => 'Super Admin',
            'email' => 'super@gmail.com',
            'email_verified_at' => now(),
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
            'remember_token' => Null,
        ]);

        // **Create System Admin User**
        $systemAdmin = User::create([
            'name' => 'System Admin',
            'email' => 'system_admin@gmail.com',
            'email_verified_at' => now(),
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
            'remember_token' => Null,
        ]);

        $facultyAdmin = User::create([
            'name' => 'Faculty Admin',
            'email' => 'faculty_admin@gmail.com',
            'email_verified_at' => now(),
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
            'remember_token' => Null,
        ]);

        // **Create Regular Users**
        $users =
            [
                [
                    'id' => 29,
                    'name' => 'دكتور /سعد بن علي الجلعود',
                    'nickname' => 'doctor',
                    'ar_name' => 'سعد بن علي الجلعود',
                    'en_name' => 'saad bn ali galaaoold',
                    'phone' => '966557767665',
                    'username' => 'Doctorsaad',
                    'email' => 'saad121@gmail.com',
                    'faculty_id' => 13,
                    'department_id' => 16,
                    'position_id' => 5,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 1,
                ],
                [
                    'id' => 30,
                    'name' => 'دكتور / عبدالكريم بن ناصر  البرادى',
                    'nickname' => 'doctor',
                    'ar_name' => 'عبدالكريم بن ناصر البرادى',
                    'en_name' => 'abdelkarim bn nasr el-baradi',
                    'phone' => '966562373739',
                    'username' => 'Abdelkarim',
                    'email' => 'abdelkarim12@gmail.com',
                    'faculty_id' => 13,
                    'department_id' => 16,
                    'position_id' => 4,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 2,
                ],
                [
                    'id' => 31,
                    'name' => 'دكتورة/ امل بنت احمد الريبش',
                    'nickname' => 'doctor',
                    'ar_name' => 'امل بنت احمد الريبش',
                    'en_name' => 'aml bnt ahmed el-rebesh',
                    'phone' => '966567878787',
                    'username' => 'Aml',
                    'email' => 'Aml1212@gmail.com',
                    'faculty_id' => 13,
                    'department_id' => 16,
                    'position_id' => 1,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 3,
                ],
                [
                    'id' => 32,
                    'name' => 'دكتور / إبراهيم بن سليمان اللاحم',
                    'nickname' => 'doctor',
                    'ar_name' => 'إبراهيم بن سليمان اللاحم',
                    'en_name' => 'ibrahim bn soliman el-lahem',
                    'phone' => '966548383833',
                    'username' => 'doctoribrahim',
                    'email' => 'doctorebrahim22@gmail.com',
                    'faculty_id' => 10,
                    'department_id' => 13,
                    'position_id' => 5,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 4,
                ],
                [
                    'id' => 33,
                    'name' => 'دكتور / سلطان بن سليمان العضيبى',
                    'nickname' => 'doctor',
                    'ar_name' => 'سلطان بن سليمان العضيبى',
                    'en_name' => 'sultan bn soliman eladepi',
                    'phone' => '966566787666',
                    'username' => 'doctorsultan',
                    'email' => 'drsultan@gmail.com',
                    'faculty_id' => 10,
                    'department_id' => 13,
                    'position_id' => 4,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 5,
                ],
                [
                    'id' => 34,
                    'name' => 'دكتور / فهد سليمان نزال الحربى',
                    'nickname' => 'doctor',
                    'ar_name' => 'فهد سليمان نزال الحربى',
                    'en_name' => 'fahd soliman nezal el-harby',
                    'phone' => '966567363333',
                    'username' => 'doctortfahd',
                    'email' => 'fahd22@gmail.com',
                    'faculty_id' => 10,
                    'department_id' => 13,
                    'position_id' => 1,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 1,
                ],
                [
                    'id' => 35,
                    'name' => 'دكتور /د/ عبدالمجيد بن عبدالله القسومي',
                    'nickname' => 'doctor',
                    'ar_name' => 'عبدالمجيد بن عبدالله القسومي',
                    'en_name' => 'abdelmeged bn aabdallah el-kasomi',
                    'phone' => '966545444444',
                    'username' => 'doctorabdelmeged',
                    'email' => 'drabdemeged21@gmail.com',
                    'faculty_id' => 12,
                    'department_id' => 14,
                    'position_id' => 5,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 2,
                ],
                [
                    'id' => 36,
                    'name' => 'دكتور / ياسر بن صالح المقبل',
                    'nickname' => 'doctor',
                    'ar_name' => 'ياسر بن صالح المقبل',
                    'en_name' => 'yasser bn saleh el-mokbel',
                    'phone' => '966563373733',
                    'username' => 'dryasser',
                    'email' => 'dryasser22@gmail.com',
                    'faculty_id' => 12,
                    'department_id' => 14,
                    'position_id' => 4,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 3,
                ],
                [
                    'id' => 37,
                    'name' => 'دكتور / وليد بن محمد الطويان',
                    'nickname' => 'doctor',
                    'ar_name' => 'وليد بن محمد الطويان',
                    'en_name' => 'wlaid bn mohamed el-tawian',
                    'phone' => '966567777666',
                    'username' => 'walid',
                    'email' => 'walid@gmail.com',
                    'faculty_id' => 12,
                    'department_id' => 14,
                    'position_id' => 1,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 4,
                ],
                [
                    'id' => 38,
                    'name' => 'د/ عائشة بنت ناصر البطاح',
                    'nickname' => 'doctor',
                    'ar_name' => 'عائشة بنت ناصر البطاح',
                    'en_name' => 'Aisha bnt naser el-batah',
                    'phone' => '966565656454',
                    'username' => 'Aisha',
                    'email' => 'Aisha@gmail.com',
                    'faculty_id' => 11,
                    'department_id' => 10,
                    'position_id' => 5,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 5,
                ],
                [
                    'id' => 39,
                    'name' => 'أستاذة /هيفاء بنت سليمان الحربي',
                    'nickname' => 'prof',
                    'ar_name' => 'هيفاء بنت سليمان الحربي',
                    'en_name' => 'haifaa bnt soliman el-harbi',
                    'phone' => '966554455555',
                    'username' => 'haifaabntsoliman',
                    'email' => 'haifaa@gmail.com',
                    'faculty_id' => 11,
                    'department_id' => 10,
                    'position_id' => 4,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 1,
                ],
                [
                    'id' => 40,
                    'name' => 'دكتورة/ مها صلاح الدين محمد',
                    'nickname' => 'prof',
                    'ar_name' => 'مها صلاح الدين محمد',
                    'en_name' => 'maha salah elden mohamed',
                    'phone' => '966544334566',
                    'username' => 'maha',
                    'email' => 'maha55@gmail.com',
                    'faculty_id' => 11,
                    'department_id' => 10,
                    'position_id' => 1,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 2,
                ],
                [
                    'id' => 41,
                    'name' => 'أ.د. علي بن عمر السحيباني',
                    'nickname' => 'prof',
                    'ar_name' => 'علي بن عمر السحيباني',
                    'en_name' => 'Ali bn omar shpani',
                    'phone' => '966545758173',
                    'username' => 'ali',
                    'email' => 'dra0545@gmail.com',
                    'faculty_id' => 10,
                    'department_id' => 13,
                    'position_id' => 3,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 3,
                ],
                [
                    'id' => 42,
                    'name' => 'أ.د. محمد بن حمد المحيميد',
                    'nickname' => 'prof',
                    'ar_name' => 'محمد بن حمد المحيميد',
                    'en_name' => 'mohamed bn hamd elmhemad',
                    'phone' => '966538673282',
                    'username' => 'mohamedbnhamed',
                    'email' => 'm-mohammeed@hotmail.com',
                    'faculty_id' => 10,
                    'department_id' => 13,
                    'position_id' => 2,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 4,
                ],
                [
                    'id' => 43,
                    'name' => 'أ.د. أحمد بن محمد البريدي',
                    'nickname' => 'prof',
                    'ar_name' => 'أحمد بن محمد البريدي',
                    'en_name' => 'ahmed bn mohamed elbradi',
                    'phone' => '966555146899',
                    'username' => 'ahmedbnmohamed',
                    'email' => 'am2121@gmail.com',
                    'faculty_id' => 10,
                    'department_id' => 13,
                    'position_id' => 1,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 5,
                ],
                [
                    'id' => 44,
                    'name' => 'أ.د / تركي بن فهد الغميز',
                    'nickname' => 'prof',
                    'ar_name' => 'تركي بن فهد الغميز',
                    'en_name' => 'turki bn fahmd elghmeez',
                    'phone' => '966556565656',
                    'username' => 'turki',
                    'email' => 'Torki2008@gmail.com',
                    'faculty_id' => 10,
                    'department_id' => 13,
                    'position_id' => 3,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 1,
                ],
                [
                    'id' => 45,
                    'name' => 'أ.د أحمد بن عبدالله الدغيري-رئيس القسم -الاستشعار في الجيومورفولوجيا',
                    'nickname' => 'prof',
                    'ar_name' => 'أحمد بن عبدالله الدغيري',
                    'en_name' => 'ahmed bn abdallah eldgheri',
                    'phone' => '966534343343',
                    'username' => 'ahmedbnabdllah',
                    'email' => 'adgierie@qu.edu.sa',
                    'faculty_id' => 11,
                    'department_id' => 10,
                    'position_id' => 3,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 2,
                ],
                [
                    'id' => 46,
                    'name' => 'أ.د عبدالله عبدالرحمن المسند -متقاعد- جغرافية المناخ',
                    'nickname' => 'prof',
                    'ar_name' => 'عبدالله بن عبدالرحمن المسند ',
                    'en_name' => 'abdallah bn abdelrahman elmosnd',
                    'phone' => '966556565765',
                    'username' => 'abdallah',
                    'email' => 'aamsnd@qu.edu.sa',
                    'faculty_id' => 11,
                    'department_id' => 10,
                    'position_id' => 2,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 3,
                ],
                [
                    'id' => 47,
                    'name' => 'أ.د حسين أحمد المحمد -النظم في المناخ',
                    'nickname' => 'prof',
                    'ar_name' => 'سين  بن أحمد المحمد ',
                    'en_name' => 'hussien bn ahmed el mohamed',
                    'phone' => '966576272727',
                    'username' => 'hussien',
                    'email' => 'hussien@gmail.com',
                    'faculty_id' => 11,
                    'department_id' => 10,
                    'position_id' => 1,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 4,
                ],
                [
                    'id' => 48,
                    'name' => 'أ.د /الطيب الامين محمد عيد',
                    'nickname' => 'prof',
                    'ar_name' => 'الطيب الامين محمد عيد',
                    'en_name' => 'Eltayb elamin mohamed eid',
                    'phone' => '966556565757',
                    'username' => 'eltaybelamin',
                    'email' => 'eem.eid@qu.edu.sa',
                    'faculty_id' => 12,
                    'department_id' => 14,
                    'position_id' => 3,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 5,
                ],
                [
                    'id' => 49,
                    'name' => 'أ.د /حبيب الله خليل الله عبد العزيز',
                    'nickname' => 'prof',
                    'ar_name' => 'حبيب الله خليل الله ع',
                    'en_name' => 'hbebe alalh khalel alah',
                    'phone' => '966565446999',
                    'username' => 'habebalalh',
                    'email' => 'h.abdulaziz@qu.edu.sa',
                    'faculty_id' => 12,
                    'department_id' => 14,
                    'position_id' => 2,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 1,
                ],
                [
                    'id' => 50,
                    'name' => 'أ / نفين عبد اللطيف  بن محمد',
                    'nickname' => 'prof',
                    'ar_name' => 'نفين عبد اللطيف بن محمد',
                    'en_name' => 'neven abdellatif bn  mohamed',
                    'phone' => '966548866767',
                    'username' => 'neven',
                    'email' => 'n.ghazali@qu.edu.sa',
                    'faculty_id' => 12,
                    'department_id' => 14,
                    'position_id' => 1,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 2,
                ],
                [
                    'id' => 51,
                    'name' => 'أ.د/ اسماعيل عبدالرحمن علي السحيباني - الدراسات اللغوية',
                    'nickname' => 'prof',
                    'ar_name' => 'اسماعيل عبدالرحمن علي السحيباني',
                    'en_name' => 'ismail abdelrahman ali el shabnai',
                    'phone' => '966556757867',
                    'username' => 'ismail',
                    'email' => 'suhaibani@qu.edu.sa',
                    'faculty_id' => 13,
                    'department_id' => 16,
                    'position_id' => 3,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 3,
                ],
                [
                    'id' => 52,
                    'name' => 'أ.د /احمد محمد عبدالرحمن حسانين - الدراسات اللغوية',
                    'nickname' => 'prof',
                    'ar_name' => 'احمد محمد عبدالرحمن حسانين',
                    'en_name' => 'ahmed mohamed abdelrahman hsanin',
                    'phone' => '966556576565',
                    'username' => 'ahmed',
                    'email' => 'amhsanien@qu.edu.sa',
                    'faculty_id' => 13,
                    'department_id' => 16,
                    'position_id' => 2,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 4,
                ],
                [
                    'id' => 53,
                    'name' => 'أ / خالد صالح حمد الشبل - الدراسات اللغوية',
                    'nickname' => 'prof',
                    'ar_name' => 'خالد صالح حمد الشبل ',
                    'en_name' => 'khaled saleh hamd elshebl',
                    'phone' => '966576575765',
                    'username' => 'khaled',
                    'email' => 'kshbl@qu.edu.sa',
                    'faculty_id' => 13,
                    'department_id' => 16,
                    'position_id' => 1,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 5,
                ],
                [
                    'id' => 54,
                    'name' => 'admin',
                    'nickname' => 'admin',
                    'ar_name' => 'ادمن كلية الشريعه والاداب',
                    'en_name' => 'admin faculty shareia adap',
                    'phone' => '966567765460',
                    'username' => 'admin',
                    'email' => 'admin21@gmail.com',
                    'faculty_id' => 10,
                    'department_id' => 13,
                    'position_id' => NULL,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 1,
                ],
                [
                    'id' => 55,
                    'name' => 'adminfaculty2',
                    'nickname' => 'admin',
                    'ar_name' => 'ادمن ادمن ادمن ادمن',
                    'en_name' => 'admin admin admin admin',
                    'phone' => '966576563727',
                    'username' => 'admin',
                    'email' => 'admin222@gmail.com',
                    'faculty_id' => 11,
                    'department_id' => 10,
                    'position_id' => NULL,
                    'headquarter_id' => 6,
                    'acadimic_rank_id' => 2,
                ],
                [
                    'id' => 56,
                    'name' => 'adminfaculty3',
                    'nickname' => 'admin',
                    'ar_name' => 'ادمن ادمن ادمن ادمن',
                    'en_name' => 'admin admin admin admin',
                    'phone' => '966565654433',
                    'username' => 'adminfaculty3',
                    'email' => 'admin2244@gmail.com',
                    'faculty_id' => 12,
                    'department_id' => 14,
                    'position_id' => NULL,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 3,
                ],
                [
                    'id' => 57,
                    'name' => 'adminfaculty4',
                    'nickname' => 'admin',
                    'ar_name' => 'ادمن ادمن ادمن ادمن',
                    'en_name' => 'admin admin admin admin',
                    'phone' => '966554436373',
                    'username' => 'admin',
                    'email' => 'admin44@gmail.com',
                    'faculty_id' => 13,
                    'department_id' => 16,
                    'position_id' => NULL,
                    'headquarter_id' => 7,
                    'acadimic_rank_id' => 4,
                ],
            ];

        // **Create Roles**
        $superAdminRole = Role::where('name', 'Super Admin')->first();
        $systemAdminRole = Role::where('name', 'System Admin')->first();
        $facultyAdminRole = Role::where('name', 'Faculty Admin')->first();
        $userRole = Role::where('name', 'Member')->first();

        // **Assign Roles to Users**
        $superAdmin->assignRole($superAdminRole);
        $systemAdmin->assignRole($systemAdminRole);
        $facultyAdmin->assignRole($facultyAdminRole);

        foreach ($users as $userData) {
            // $user = User::create($userData);  // Capture the created user instance
            // Capture the created user instance
            $user = User::create([
                'id' => $userData['id'],
                'name' => $userData['name'],
                'nickname' => $userData['nickname'],
                'username' => $userData['username'],
                'ar_name' => $userData['ar_name'],
                'en_name' => $userData['en_name'],
                'email' => $userData['email'],
                // 'password' => $userData['password'],
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
                'phone' => $userData['phone'],
                'headquarter_id' => $userData['headquarter_id'],
                'department_id' => $userData['department_id'],
                'position_id' => $userData['position_id'],
                'acadimic_rank_id' => $userData['acadimic_rank_id'],
                'faculty_id' => $userData['faculty_id'],
                'is_active' => 1,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            $user->assignRole($userRole);  // Assign role to the created user
        }
    }
}
